// load state Config
const LOAD_STATE_CONFIG = 'LOAD_STATE_CONFIG';

// message scaping actions
const POPULATE_DATA = 'POPULATE_DATA';
const STORE_MESSAGES = 'STORE_MESSAGES';
const GET_COLLECTION = 'GET_COLLECTION';
const GET_BALANCES = 'GET_BALANCES';
const SELECT_PROVIDER_TYPE = 'SELECT_PROVIDER_TYPE';

// auth action types
const SIGN_OUT = 'SIGN_OUT';
const SET_INITIAL_USER_STATE = 'SET_INITIAL_USER_STATE';
const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
const SIGN_IN_WITH_GOOGLE = 'SIGN_IN_WITH_GOOGLE';
const SIGN_IN_WITH_PHONE_NUMBER = 'SIGN_IN_WITH_PHONE_NUMBER';
const OTP_LOGIN_SUCCESS = 'OTP_LOGIN_SUCCESS';
const GOOGLE_VERIFICATION = 'GOOGLE_VERIFICATION';
const PHONE_NO_VERIFICATION = 'PHONE_NO_VERIFICATION';
const USER_VERIFIED = 'USER_VERIFIED';
const AGGREGATED_DATA = 'AGGREGATED_DATA';

export {
  LOAD_STATE_CONFIG,
  POPULATE_DATA,
  STORE_MESSAGES,
  GET_COLLECTION,
  SELECT_PROVIDER_TYPE,
  SIGN_IN_ERROR,
  SIGN_OUT,
  SIGN_IN_WITH_GOOGLE,
  SIGN_IN_WITH_PHONE_NUMBER,
  OTP_LOGIN_SUCCESS,
  SET_INITIAL_USER_STATE,
  GOOGLE_VERIFICATION,
  PHONE_NO_VERIFICATION,
  USER_VERIFIED,
  AGGREGATED_DATA,
  GET_BALANCES,
};
