// load state Config
const LOAD_STATE_CONFIG = 'LOAD_STATE_CONFIG';

// message scaping actions
const POPULATE_DATA = 'POPULATE_DATA';
const STORE_MESSAGES = 'STORE_MESSAGES';
const GET_COLLECTION = 'GET_COLLECTION';

// auth action types
const SIGN_OUT = 'SIGN_OUT';
const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
const SIGN_IN_WITH_GOOGLE = 'SIGN_IN_WITH_GOOGLE';
const SIGN_IN_WITH_PHONE_NUMBER = 'SIGN_IN_WITH_PHONE_NUMBER';
const OTP_LOGIN_SUCCESS = 'OTP_LOGIN_SUCCESS';

export {
  LOAD_STATE_CONFIG,
  POPULATE_DATA,
  STORE_MESSAGES,
  GET_COLLECTION,
  SIGN_IN_ERROR,
  SIGN_OUT,
  SIGN_IN_WITH_GOOGLE,
  SIGN_IN_WITH_PHONE_NUMBER,
  OTP_LOGIN_SUCCESS,
};
