export const typesData = [
  {
    id: 1,
    title: 'All',
    value: '',
    image: require('../assets/buttons/All.png'),
    amount: 'k1000',
    colors: ['#5a60f8', '#5a60f8', '#8387f9'],
  },
  {
    id: 2,
    title: 'Sent',
    value: 'Sent',
    image: require('../assets/buttons/Sent.png'),
    amount: 'k130000',
    colors: ['#ff5252', '#ff7d7d', '#ff7d7d'],
  },
  {
    id: 3,
    title: 'Receive',
    value: 'Receive',
    image: require('../assets/buttons/Receive.png'),
    amount: 'k1700',
    colors: ['#39b54b', '#39b54b', '#65cd73'],
  },
  {
    id: 4,
    title: 'Deposit',
    value: 'Deposit',
    image: require('../assets/buttons/Deposit.png'),
    amount: 'k500',
    colors: ['#5b64ae', '#5b64ae', '#848ac2'],
  },
  {
    id: 5,
    title: 'Withdraw',
    value: 'Withdraw',
    image: require('../assets/buttons/Withdraw.png'),
    amount: 'K100',
    colors: ['#ed6e25', '#ed6e25', '#f1925b'],
  },
  {
    id: 6,
    title: 'PayBill',
    value: 'PayBill',
    image: require('../assets/buttons/PayBill.png'),
    amount: 'k30000',
    colors: ['#fed304', '#fed304', '#fedd42'],
  },
  {
    id: 7,
    title: 'BuyGoods',
    value: 'BuyGoods',
    image: require('../assets/buttons/BuyGoods.png'),
    amount: 'k4000',
    colors: ['#880085', '#880085', '#e500e0'],
  },
  {
    id: 8,
    title: 'Airtime',
    value: 'Airtime',
    image: require('../assets/buttons/Airtime.png'),
    amount: 'k5000',
    colors: ['#f33c7E', '#f33c7E', '#f56c9e'],
  },
  {
    id: 9,
    title: 'Reverse',
    value: 'Reverse',
    image: require('../assets/buttons/Reverse.png'),
    amount: 'k7700',
    colors: ['#9c5518', '#9c5518', '#de7c28'],
  },
];